#!/bin/csh
setenv SSR_DIRECTORY $0:h
setenv PYTHONPATH "/home/greta/Tools/SSRVisualizer/"
cd ${SSR_DIRECTORY}
unsetenv PERL5LIB
source "/proj/sot/ska3/flight/bin/ska_envs.csh"
/proj/sot/ska3/flight/bin/python3.12 "/home/greta/Tools/SSRVisualizer/"