#!/bin/csh
setenv SSR_DIRECTORY $0:h
setenv PYTHONPATH "/home/rhoover/python/Code/ccdm/SSR Visualizer/"
cd ${SSR_DIRECTORY}
unsetenv PERL5LIB
source "/proj/sot/ska3/flight/bin/ska_envs.csh"
/proj/sot/ska3/flight/bin/python "/home/rhoover/python/Code/ccdm/SSR Visualizer/main.py"